import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import HeaderWithCart from "./ui/HeaderWithCart";
import StoreProvider from "./StoreProvider";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lemonade Stand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={`${instrumentSans.variable} antialiased`}>
          <HeaderWithCart />
          <main>{children}</main>
        </body>
      </StoreProvider>
    </html>
  );
}
