import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lemonade Stand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${instrumentSans.variable} antialiased`}>
        <header className="flex flex-row justify-between uppercase font-semibold px-10 py-5">
          <nav className="space-x-10">
            <Link href="/">Home</Link>
            <Link href="/manageStore">Manage store</Link>
          </nav>
          <button className="uppercase">Cart</button>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
